로그인 버튼 페이지 추가
itslaves/rentalgames-front pull request #14
Opened 2019-06-24 01:59 UTC by freddieyyh

서버로부터 Oauth정보를 받아서 로그인 버튼을 그려주도록 수정해보았습니다.

2019-06-25 04:16 UTC, skyoo2003 commented
로그인 버튼이 API 요청 후에 사용 가능해지는 만큼 처리중인 상황을 표시해주고, 처리중일 땐 버튼이 disabled 되면 좋을 것 같습니다.

처리중인 상황은 loading ux 아니면 skeleton ux 형식이면 되지 않을까 싶어여

2019-06-25 04:23 UTC, skyoo2003 requested changes

2019-06-25 04:23 UTC, skyoo2003 commented on src/stories/GoogleLoginButton.stories.js
>  /* eslint-disable import/no-extraneous-dependencies */
해당 파일의 이름 변경이 필요합니다

2019-06-25 04:23 UTC, skyoo2003 commented on src/views/Login.vue
> +    this.$http.get('/vendors')
- API 서버가 다른 주소로 떠있는 상황도 고려해야할 것 같습니다. (대신에 도메인을 맞추는 걸 정책으로 잡아서 크로스 도메인 이슈는 회피하면 될 것 같구여)

- 'GET /auth/vendors' URL 경로로 하는게 어떨까여?

2019-06-25 05:13 UTC, freddieyyh commented on src/views/Login.vue
> +    this.$http.get('/vendors')
이건 임의로 적어놓은거긴한데, api서버 path와 맞춰놓을게요~

2019-06-25 23:15 UTC, freddieyyh commented on src/stories/GoogleLoginButton.stories.js
>  /* eslint-disable import/no-extraneous-dependencies */
변경했습니다~

2019-06-25 23:15 UTC, freddieyyh commented on src/views/Login.vue
> +    this.$http.get('/vendors')
api host를 환경변수로 받도록 수정했습니다.

2019-06-25 23:19 UTC, skyoo2003 approved these changes
😃👍

2019-06-28 12:32 UTC, skyoo2003 commented
- 로그인 시나리오 추가 (mock)
- 정보 못가져왔을 때 뭔가 잘못된걸 알 수 있게 화면 보여주기

2019-06-29 23:09 UTC, skyoo2003 requested changes
지난번 논의때 나온 내용만 추가적으로 포함 부탁드려여~
- 로그인 시나리오 추가 (mock)
- 로그인 화면 정보 못가져왔을 때 뭔가 잘못된걸 알 수 있게 화면 보여주기

2019-06-30 02:48 UTC, hayden-han approved these changes

2019-07-01 04:46 UTC, skyoo2003 approved these changes

2019-07-01 04:47 UTC, merged