login버튼 단위테스트 추가.
itslaves/rentalgames-front pull request #27
Opened 2019-08-13 11:25 UTC by haningyu

2019-08-13 12:58 UTC, skyoo2003 commented
Refer https://github.com/itslaves/rentalgames-front/issues/25

2019-08-13 13:02 UTC, skyoo2003 requested changes
파일명에 vue 확장자는 안들어가도 될 것 같습니다.

LoginButton.vue.spec.js -> LoginButton.spec.js

2019-08-13 22:48 UTC, haningyu commented
> 파일명에 vue 확장자는 안들어가도 될 것 같습니다.
> 
> LoginButton.vue.spec.js -> LoginButton.spec.js

아 오키오키 오전에 이름바꿔 푸쉬할게염

2019-08-14 01:18 UTC, skyoo2003 approved these changes

2019-08-14 01:50 UTC, merged